name: Build GUI EXE with PyInstaller (Windows)

on:
  push:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          if exist requirements.txt pip install -r requirements.txt
          pip install pyinstaller

      - name: Build onefile (GUI)
        shell: cmd
        run: |
          pyinstaller --noconfirm --onefile --windowed --name MyApp .\main.py

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-windows-exe
          path: dist\MyApp.exe
